apiVersion: vstar.my.birdhk/v1
kind: Logstash
metadata:
  name: logstash-sample
  namespace: logstash-operator-system
spec:
  replicas: 1
  image: "opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2"
  namespace: "logstash-operator-system"