apiVersion: vstar.my.birdhk/v1
kind: Logstash
metadata:
  name: opensearch-logstash
  namespace: logstash-operator-system
spec:
  replicas: 1
  image: "opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2"